# Form implementation generated from reading ui file 'clock.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TomatoClock(object):
    def setupUi(self, TomatoClock):
        TomatoClock.setObjectName("TomatoClock")
        TomatoClock.resize(416, 300)
        TomatoClock.setAccessibleName("")
        self.label_state = QtWidgets.QLabel(parent=TomatoClock)
        self.label_state.setGeometry(QtCore.QRect(10, 114, 81, 27))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.label_state.setFont(font)
        self.label_state.setObjectName("label_state")
        self.state = QtWidgets.QLabel(parent=TomatoClock)
        self.state.setGeometry(QtCore.QRect(97, 114, 81, 27))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.state.setFont(font)
        self.state.setObjectName("state")
        self.time = QtWidgets.QLabel(parent=TomatoClock)
        self.time.setGeometry(QtCore.QRect(16, 10, 384, 96))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(72)
        font.setUnderline(False)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.pushButton = QtWidgets.QPushButton(parent=TomatoClock)
        self.pushButton.setGeometry(QtCore.QRect(170, 160, 75, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.toolButton = QtWidgets.QToolButton(parent=TomatoClock)
        self.toolButton.setGeometry(QtCore.QRect(380, 270, 24, 22))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(TomatoClock)
        QtCore.QMetaObject.connectSlotsByName(TomatoClock)

    def retranslateUi(self, TomatoClock):
        _translate = QtCore.QCoreApplication.translate
        TomatoClock.setWindowTitle(_translate("TomatoClock", "TomatoClock"))
        self.label_state.setText(_translate("TomatoClock", "状态："))
        self.state.setText(_translate("TomatoClock", "暂停中"))
        self.time.setText(_translate("TomatoClock", "00:00:00"))
        self.pushButton.setText(_translate("TomatoClock", "开始"))
        self.toolButton.setText(_translate("TomatoClock", "..."))
