# Form implementation generated from reading ui file 'tool.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tool(object):
    def setupUi(self, Tool):
        Tool.setObjectName("Tool")
        Tool.resize(301, 149)
        self.label_work = QtWidgets.QLabel(parent=Tool)
        self.label_work.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_work.setFont(font)
        self.label_work.setObjectName("label_work")
        self.label_rest = QtWidgets.QLabel(parent=Tool)
        self.label_rest.setGeometry(QtCore.QRect(10, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_rest.setFont(font)
        self.label_rest.setObjectName("label_rest")
        self.worktime_h = QtWidgets.QLineEdit(parent=Tool)
        self.worktime_h.setGeometry(QtCore.QRect(160, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.worktime_h.setFont(font)
        self.worktime_h.setInputMask("")
        self.worktime_h.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worktime_h.setObjectName("worktime_h")
        self.worktime_m = QtWidgets.QLineEdit(parent=Tool)
        self.worktime_m.setGeometry(QtCore.QRect(230, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.worktime_m.setFont(font)
        self.worktime_m.setInputMask("")
        self.worktime_m.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worktime_m.setObjectName("worktime_m")
        self.resttime_h = QtWidgets.QLineEdit(parent=Tool)
        self.resttime_h.setGeometry(QtCore.QRect(160, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.resttime_h.setFont(font)
        self.resttime_h.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.resttime_h.setInputMask("")
        self.resttime_h.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resttime_h.setObjectName("resttime_h")
        self.resttime_m = QtWidgets.QLineEdit(parent=Tool)
        self.resttime_m.setGeometry(QtCore.QRect(230, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.resttime_m.setFont(font)
        self.resttime_m.setInputMask("")
        self.resttime_m.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resttime_m.setObjectName("resttime_m")
        self.SaveButton = QtWidgets.QPushButton(parent=Tool)
        self.SaveButton.setGeometry(QtCore.QRect(210, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")

        self.retranslateUi(Tool)
        QtCore.QMetaObject.connectSlotsByName(Tool)

    def retranslateUi(self, Tool):
        _translate = QtCore.QCoreApplication.translate
        Tool.setWindowTitle(_translate("Tool", "Tool"))
        self.label_work.setText(_translate("Tool", "WorkTime"))
        self.label_rest.setText(_translate("Tool", "RestTime"))
        self.worktime_h.setText(_translate("Tool", "0"))
        self.worktime_m.setText(_translate("Tool", "25"))
        self.resttime_h.setText(_translate("Tool", "0"))
        self.resttime_m.setText(_translate("Tool", "5"))
        self.SaveButton.setText(_translate("Tool", "保存"))
